version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "443"
      - "8001"
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend-envoy.yaml:/etc/frontend-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - frontend
    environment:
      - SERVICE_NAME=frontend
    expose:
      - "80"

  umbrella:
    build:
      context: ../platform_umbrella
      dockerfile: Dockerfile
    volumes:
      - ./umbrella-envoy.yaml:/etc/umbrella-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - umbrella
    environment:
      - SERVICE_NAME=umbrella
    expose:
      - "80"

networks:
  envoymesh: {}
