FROM envoyproxy/envoy:latest

ADD ./cryptowise-ai.crt /etc/cryptowise-ai.crt
ADD ./cryptowise-ai.key /etc/cryptowise-ai.key
ADD ./platform-web.ai.pem /etc/platform-web.ai.pem
ADD ./api-platform-web.ai.pem /etc/api-platform-web.ai.pem

RUN apt-get update && apt-get -q install -y \
    curl
CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
